name: Build & Test Topn

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build_package:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PGVERSION:
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone tools branch
        run: git clone -b v0.8.18 --depth=1  https://github.com/citusdata/tools.git tools

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Before Install
        run: |
          ./test_data_provider
          sudo make -C tools install
          setup_apt
          nuke_pg
        env:
          PGVERSION: ${{ matrix.PGVERSION }}

      - name: Install
        run: |
          install_uncrustify
          install_pg
        env:
          PGVERSION: ${{ matrix.PGVERSION }}

      - name: Before Script
        run: |
          citus_indent --quiet --check
          config_and_start_cluster
        env:
          PGVERSION: ${{ matrix.PGVERSION }}

      - name: Script
        run: |
          pg_travis_test
        env:
          PGVERSION: ${{ matrix.PGVERSION }}
